# Generated by Django 4.2.17 on 2024-12-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='thumbnail',
        ),
    ]
