# Generated by Django 4.2.17 on 2025-01-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('apartmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='apartmentapp.transaction'),
        ),
    ]
