# Generated by Django 4.2.17 on 2025-01-01 07:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
