# Generated by Django 4.2.17 on 2025-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0002_remove_questionoption_question_question_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(related_name='questions', to='apartmentapp.questionoption'),
        ),
    ]
