# Generated by Django 4.2.17 on 2025-01-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0002_alter_reflection_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
    ]
