# Generated by Django 4.2.17 on 2025-01-03 02:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apartmentapp', '0002_monthlyfee_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyfee',
            unique_together={('room', 'fee', 'created_date', 'status', 'transaction')},
        ),
    ]
