# Generated by Django 4.2.17 on 2025-01-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0003_alter_package_thumbnail_alter_transaction_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package',
            new_name='storage_locker',
        ),
    ]
