# Generated by Django 4.2.17 on 2025-01-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0003_room_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Success', 'SUCCESS'), ('Fail', 'FAIL')], default='Pending', max_length=20),
        ),
    ]
