# Generated by Django 4.2.17 on 2025-01-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apartmentapp', '0003_alter_monthlyfee_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Success', 'SUCCESS'), ('Fail', 'FAIL')],
                                   default='Pending', max_length=20),
        ),
    ]
