# Generated by Django 4.2.17 on 2025-01-03 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('apartmentapp', '0004_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfee',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='apartmentapp.transaction'),
        ),
    ]
