# Generated by Django 4.2.17 on 2025-01-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0004_rename_package_package_storage_locker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='storage_locker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='apartmentapp.storagelocker'),
        ),
    ]
