# Generated by Django 4.2.17 on 2025-01-04 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0005_alter_monthlyfee_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfee',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartmentapp.transaction'),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecard',
            unique_together={('user', 'vehicle_number')},
        ),
        migrations.RemoveField(
            model_name='vehiclecard',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='vehiclecard',
            name='relationship',
        ),
    ]
