# Generated by Django 4.2.17 on 2025-01-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0005_alter_package_storage_locker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
