# Generated by Django 4.2.17 on 2025-01-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0006_alter_monthlyfee_transaction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclecard',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vehiclecard',
            name='citizen_card',
            field=models.CharField(default=None, max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclecard',
            name='full_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclecard',
            name='relationship',
            field=models.CharField(choices=[('Apartment owner', 'APARTMENT_OWNER'), ('Relative', 'RELATIVE')], default='Apartment owner', max_length=20),
        ),
    ]
