# Generated by Django 4.2.17 on 2025-01-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0006_alter_package_pickup_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('Not received', 'NOT_RECEIVED'), ('Received', 'RECEIVED')], default='Not received', max_length=20),
        ),
    ]
