# Generated by Django 4.2.17 on 2025-01-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0007_alter_vehiclecard_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclecard',
            name='expiration_date',
        ),
    ]
