# Generated by Django 4.2.17 on 2025-01-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0008_remove_vehiclecard_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='vehiclecard',
            unique_together={('vehicle_number', 'citizen_card', 'active', 'user')},
        ),
    ]
