# Generated by Django 4.2.17 on 2025-01-04 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0008_feedback_feedbackresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='feedback',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='apartmentapp.feedback'),
        ),
    ]
