# Generated by Django 4.2.17 on 2025-01-04 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0009_alter_feedbackresponse_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
