# Generated by Django 4.2.17 on 2025-01-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0009_fee_value_alter_vehiclecard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecard',
            name='citizen_card',
            field=models.CharField(max_length=30),
        ),
    ]
