# Generated by Django 4.2.17 on 2025-01-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0010_alter_feedback_resident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='status',
            field=models.CharField(choices=[('In progress', 'IN_PROGRESS'), ('Resolved', 'RESOLVED')], default='In progress', max_length=20),
        ),
    ]
