# Generated by Django 4.2.17 on 2025-01-09 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0010_alter_vehiclecard_citizen_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfee',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apartmentapp.transaction'),
        ),
    ]
