# Generated by Django 4.2.17 on 2025-01-04 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0011_alter_feedback_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_locker', to=settings.AUTH_USER_MODEL),
        ),
    ]
