# Generated by Django 4.2.17 on 2025-01-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0011_alter_monthlyfee_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyfee',
            name='description',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
