# Generated by Django 4.2.17 on 2025-01-10 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0012_monthlyfee_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyfee',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_fees', to='apartmentapp.transaction'),
        ),
    ]
