# Generated by Django 4.2.17 on 2025-01-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0013_question_survey_response_questionoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selected_options',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='answers', to='apartmentapp.questionoption'),
        ),
    ]
