# Generated by Django 4.2.17 on 2025-01-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartmentapp', '0013_alter_monthlyfee_transaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehiclecard',
            unique_together={('vehicle_number', 'citizen_card', 'full_name', 'user')},
        ),
    ]
